### ISSUE TITLE
New Year same problem as last year (no popups)

### ISSUE THREAD

**Issue by Bentic77** [Exslims/MercuryTrade#404]
Hi, since 2020 no popup apears on trade like on 1.1.2019
If i change my system date to  2019 it works fine. can we have a fix please?
thanks

**Comment by rdavid66** [comment]
Just use the newest release.

**Comment by Bentic77** [comment]
ah thanks, didnt see the new release.

**Comment by HiPoEGH** [comment]
Same issue. Using newest release.

**Comment by igorlcs** [comment]
Same issue, and im using newest release too...

**Comment by DamnNewbie** [comment]
Same problem for me.  No notifications and stash tab grid stopped working.  I updated to newest release last week and all was good until 1/1/2020.

**Comment by jckesser** [comment]
same issue here only it I get some pop ups and not others, new year seams about right to me too

**Comment by BloodyShrapnel** [comment]
Same here. As soon as I change the year to 2019, it works again with latest version.

**Comment by Exslims** [comment]
Guys, just download the latest version, it should fix this problem..

**Comment by jgz** [comment]
I'm using 1.0.3.5 and it was working for a day or so after I upgraded,  Then today its not showing any notifications.  Also when I go to tests it doesn't show them either.

How do i reset all the settings so I can try it with a fresh install?

**Comment by Exslims** [comment]
https://github.com/Exslims/MercuryTrade/wiki/Troubleshooting

**Comment by jckesser** [comment]
I'm also using 1.3.0.5 and reset settings and I'm still not getting all notifications

**Comment by rdavid66** [comment]
> I'm also using 1.3.0.5 and reset settings and I'm still not getting all notifications

Theres two issues, but they are there since a very long time and isn't connected to new year in any way:
1, For some countries (usually with special characters), GGG doesn't log the messages so you don't get notification.
2, Sometimes it randomly stops working in this case just restart.

**Comment by jckesser** [comment]
> > I'm also using 1.3.0.5 and reset settings and I'm still not getting all notifications
> 
> Theres two issues, but they are there since a very long time and isn't connected to new year in any way:
> 1, For some countries (usually with special characters), GGG doesn't log the messages so you don't get notification.
> 2, Sometimes it randomly stops working in this case just restart.

I'm aware of character set issue for a long time. Also I'll restart and most times my first trade doesn't notify so it isn't that either. This is something different that is making it very unreliable

**Comment by SoM6666** [comment]
move onto a different program, this one is dead

**Comment by nick3hh** [comment]
hope it gets fixed, i cant see myself using anything else than mercurytrade
